# generated by fastapi-codegen:
#   filename:  app/openapi/petstore-expanded.yaml
#   timestamp: 2022-06-19T14:10:41+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class NewPet(BaseModel):
    name: str
    tag: Optional[str] = None


class Error(BaseModel):
    code: int
    message: str


class Pet(NewPet):
    id: int
